[project]
name = "week-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.15.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "locust>=2.46.6",
    "ollama>=0.6.2",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
    "uvicorn>=0.53.0",
]
